const TelegramBot = require('node-telegram-bot-api');
const bot = new TelegramBot('7868821401:AAEjomsl0i8GEfigrdwL1-MRSvhe8cqw_hk', {polling: true});

// ูุตุงุฆุญ ุงุญุชุฑุงููุฉ ููุนุจ ุฑูุจูููุณ
const tips = [
  "๐ฎ **ูุตูุญุฉ 1**: ุงุณุชุฎุฏู ุฒุฑ 'Shift' ููุฌุฑู ุจุณุฑุนุฉ!",
  "๐ก **ูุตูุญุฉ 2**: ุฌุฑุจ ุฃูุนุงุจ 'Obby' ูุชุญุณูู ููุงุฑุงุชู ูู ุงูููุฒ.",
  "๐ฐ **ูุตูุญุฉ 3**: ูุง ุชุดุชุฑู 'Robux' ุฅูุง ูู ุงููููุน ุงูุฑุณูู ูุชุฌูุจ ุงูุงุญุชูุงู.",
  "๐ **ูุตูุญุฉ 4**: ุดุงุฑู ูู ูุณุงุจูุงุช Roblox ุงูุฑุณููุฉ ูุฑุจุญ ุฌูุงุฆุฒ."
];

// ุนูุฏ ุฅุฑุณุงู /start
bot.onText(/\/start/, (msg) => {
  const chatId = msg.chat.id;
  bot.sendMessage(
    chatId,
    `ูุฑุญุจุงู ${msg.from.first_name}! ๐พ\n\n` +
    "ุฃูุง ุจูุช ูุณุงุนุฏ ูุชุนูู *ุงููุนุจ ุงูุงุญุชุฑุงูู ูู Roblox*.\n\n" +
    "โ ุงูุฃูุงูุฑ ุงููุชุงุญุฉ:\n" +
    "/tips - ูุตุงุฆุญ ุงุญุชุฑุงููุฉ\n" +
    "/safety - ูุตุงุฆุญ ุฃูุงู\n" +
    "/help - ุงููุณุงุนุฏุฉ",
    {parse_mode: "Markdown"}
  );
});

// ุนูุฏ ุฅุฑุณุงู /tips
bot.onText(/\/tips/, (msg) => {
  const randomTip = tips[Math.floor(Math.random() * tips.length)];
  bot.sendMessage(msg.chat.id, randomTip);
});

// ุนูุฏ ุฅุฑุณุงู /safety
bot.onText(/\/safety/, (msg) => {
  bot.sendMessage(
    msg.chat.id,
    "๐ **ูุตุงุฆุญ ุฃูุงู ูููุฉ**:\n" +
    "- ูุง ุชุดุงุฑู ูุนูููุงุช ุญุณุงุจู ูุน ุฃุญุฏ\n" +
    "- ูุนูู ุงูุชุญูู ุจุฎุทูุชูู (2FA)\n" +
    "- ุงุญุฐุฑ ูู ููุงูุน 'Robux ุงููุฌุงูู' ููู ุงุญุชูุงู",
    {parse_mode: "Markdown"}
  );
});

console.log("โ ุงูุจูุช ูุนูู! ุฃุฑุณู /start ูู Telegram");
